name: Sync Fork

on:
  push:
  schedule:
    - cron:  "*/15 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "apache/incubator-superset"
        source_branch: "0.34"
        destination_branch: "source-0.34.0"
        github_token: ${{ secrets.GITHUB_TOKEN }}
