name: Sync Fork

on: [push]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "apache/incubator-superset"
        source_branch: "master"
        destination_branch: "source"
        github_token: ${{ secrets.GITHUB_TOKEN }}
